#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shlex
import subprocess
import sys
from pathlib import Path
from typing import Any


AGENTS_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(AGENTS_ROOT))

from hooks.control_plane import load_hooks_registry, render_copilot_hooks, render_json  # noqa: E402


DEFAULT_SETTINGS_OVERLAY = AGENTS_ROOT / "config" / "copilot-settings.json"
DEFAULT_HOOKS_REGISTRY = AGENTS_ROOT / "hooks/registry.json"
DEFAULT_DEV_SERVERS_REGISTRY = AGENTS_ROOT / "dev-servers/registry.json"
DEFAULT_PREVIEW_RUNNER = AGENTS_ROOT / "scripts/run-agent-preview-server.py"
DEFAULT_COPILOT_HOME = Path.home() / ".copilot"
DEFAULT_SETTINGS_FILE = DEFAULT_COPILOT_HOME / "settings.json"
DEFAULT_USER_CONFIG_FILE = DEFAULT_COPILOT_HOME / "config.json"
DEFAULT_MCP_CONFIG_FILE = DEFAULT_COPILOT_HOME / "mcp-config.json"
DEFAULT_HOOKS_FILE = DEFAULT_COPILOT_HOME / "hooks/agents-control-plane.json"
DEFAULT_LAUNCHER_TARGET = Path.home() / "bin" / "copilot"
DEFAULT_REAL_CLI_PATH = Path("/opt/homebrew/bin/copilot")
DEFAULT_GITHUB_ROOT = Path.home() / "GitHub"
DEFAULT_APP_SUPPORT_DIR = Path.home() / "Library/Application Support/com.github.githubapp"
DEFAULT_GLOBAL_INSTRUCTIONS_SOURCE = AGENTS_ROOT / "config" / "global.agents.md"
DEFAULT_GLOBAL_INSTRUCTIONS_TARGET = DEFAULT_COPILOT_HOME / "copilot-instructions.md"

CONFIG_HEADER = "// User settings belong in settings.json.\n// This file is managed automatically.\n"
GITHUB_APP_CONFIG_HEADER = "# THIS IS AUTOGENERATED. DO NOT EDIT MANUALLY.\n"
GITHUB_APP_SERVER_READY_PATTERN = r"(?i)(https?://\S+)"
MANAGEMENT_COMMANDS = {
    "completion",
    "help",
    "init",
    "login",
    "mcp",
    "plugin",
    "skill",
    "update",
    "version",
}

TOP_LEVEL_KEYS = {"description", "hooks", "launcher", "mcpServers", "settings", "settingsPrune", "skills", "trust"}
BOOLEAN_SETTINGS = {
    "askUser",
    "beep",
    "ide.autoConnect",
    "ide.openDiffOnEdit",
    "memory",
    "notifications",
    "showTipsOnStartup",
}
BANNER_VALUES = {"always", "never", "once"}
EFFORT_LEVEL_VALUES = {"none", "low", "medium", "high", "xhigh", "max"}
TAB_IDS = {"agents", "copilot", "gists", "issues", "pull-requests"}
LAUNCHER_KEYS = {"defaultArgs", "enabled", "managementCommands"}
LAUNCHER_VALUE_FLAGS = {
    "--available-tools",
    "--disable-mcp-server",
    "--effort",
    "--excluded-tools",
    "--max-autopilot-continues",
    "--mode",
    "--model",
}
LAUNCHER_BOOLEAN_FLAGS = {"--disable-builtin-mcps", "--no-ask-user", "--yolo"}
MODE_VALUES = {"autopilot", "interactive", "plan"}
MODEL_VALUES = {"claude-sonnet-5"}
PRUNABLE_SETTINGS = {"tabs.hide"}
SKILL_DIRECTORY_POLICIES = {"empty"}
APP_SKILLS_POLICIES = {"allow-known-only"}
MCP_SERVER_TYPES = {"local", "http", "sse"}
MCP_SERVER_KEYS = {"args", "command", "env", "headers", "timeout", "tools", "type", "url"}


class CopilotSyncError(RuntimeError):
    pass


def expand_path(raw: str, home: Path) -> Path:
    if raw.startswith("~/"):
        return home / raw[2:]
    return Path(raw)


def resolve_repo_root(repo: str, github_root: Path, home: Path) -> Path:
    if repo.startswith("~/") or repo.startswith("/"):
        return expand_path(repo, home).resolve()
    return (github_root / repo).resolve()


def output_path(path: Path) -> Path:
    path = path.expanduser()
    return path if path.is_absolute() else Path.cwd() / path


def strip_json_comments(text: str) -> str:
    lines = []
    for line in text.splitlines():
        if line.lstrip().startswith("//"):
            continue
        lines.append(line)
    return "\n".join(lines).strip()


def read_json_object(path: Path, *, allow_comments: bool = False) -> dict[str, Any]:
    if not path.exists():
        return {}
    text = path.read_text(encoding="utf-8")
    if allow_comments:
        text = strip_json_comments(text)
    if not text:
        return {}
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:
        raise CopilotSyncError(f"invalid JSON in {path}: {exc}") from exc
    if not isinstance(data, dict):
        raise CopilotSyncError(f"JSON root must be an object: {path}")
    return data


def require_bool_setting(key: str, value: Any) -> None:
    if not isinstance(value, bool):
        raise CopilotSyncError(f"settings.{key} must be a boolean")


def require_string_list(key: str, value: Any) -> list[str]:
    if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
        raise CopilotSyncError(f"settings.{key} must be an array of strings")
    return value


def validate_tabs_setting(value: Any) -> None:
    if not isinstance(value, dict):
        raise CopilotSyncError("settings.tabs must be an object with hide/sort/enabled keys")
    allowed_keys = {"enabled", "hide", "sort"}
    unknown = sorted(set(value) - allowed_keys)
    if unknown:
        raise CopilotSyncError(f"settings.tabs has unknown keys: {', '.join(unknown)}")
    if "enabled" in value and not isinstance(value["enabled"], bool):
        raise CopilotSyncError("settings.tabs.enabled must be a boolean")
    for key in ("hide", "sort"):
        if key not in value:
            continue
        items = require_string_list(f"tabs.{key}", value[key])
        unknown_tabs = sorted(set(items) - TAB_IDS)
        if unknown_tabs:
            raise CopilotSyncError(f"settings.tabs.{key} has unknown tab ids: {', '.join(unknown_tabs)}")
        if key == "hide" and "copilot" in items:
            raise CopilotSyncError("settings.tabs.hide must not include copilot because the Session tab cannot be hidden")


def validate_managed_settings(settings: dict[str, Any]) -> None:
    allowed = BOOLEAN_SETTINGS | {"banner", "disabledSkills", "effortLevel", "tabs"}
    unknown = sorted(set(settings) - allowed)
    if unknown:
        raise CopilotSyncError(f"unsupported managed Copilot settings: {', '.join(unknown)}")
    for key in BOOLEAN_SETTINGS:
        if key in settings:
            require_bool_setting(key, settings[key])
    if "banner" in settings and settings["banner"] not in BANNER_VALUES:
        raise CopilotSyncError(f"settings.banner must be one of: {', '.join(sorted(BANNER_VALUES))}")
    if "effortLevel" in settings and settings["effortLevel"] not in EFFORT_LEVEL_VALUES:
        raise CopilotSyncError(f"settings.effortLevel must be one of: {', '.join(sorted(EFFORT_LEVEL_VALUES))}")
    if "disabledSkills" in settings:
        require_string_list("disabledSkills", settings["disabledSkills"])
    if "tabs" in settings:
        validate_tabs_setting(settings["tabs"])


def validate_settings_prune(settings_prune: list[str]) -> None:
    unknown = sorted(set(settings_prune) - PRUNABLE_SETTINGS)
    if unknown:
        raise CopilotSyncError(f"settingsPrune has unsupported keys: {', '.join(unknown)}")


def validate_trust(trust: dict[str, Any]) -> None:
    allowed = {"directChildren", "extraFolders", "githubRoot"}
    unknown = sorted(set(trust) - allowed)
    if unknown:
        raise CopilotSyncError(f"trust has unknown keys: {', '.join(unknown)}")
    for key in ("directChildren", "githubRoot"):
        if key in trust and not isinstance(trust[key], bool):
            raise CopilotSyncError(f"trust.{key} must be a boolean")
    if "extraFolders" in trust:
        value = trust["extraFolders"]
        if not isinstance(value, list) or not all(isinstance(item, str) and item.strip() for item in value):
            raise CopilotSyncError("trust.extraFolders must be an array of non-empty strings")


def validate_launcher_args(args: list[str]) -> None:
    idx = 0
    while idx < len(args):
        flag = args[idx]
        if flag in LAUNCHER_BOOLEAN_FLAGS:
            idx += 1
            continue
        if flag not in LAUNCHER_VALUE_FLAGS:
            raise CopilotSyncError(f"launcher.defaultArgs has unsupported flag: {flag}")
        if idx + 1 >= len(args) or args[idx + 1].startswith("--"):
            raise CopilotSyncError(f"launcher.defaultArgs flag requires a value: {flag}")
        value = args[idx + 1]
        if flag == "--effort" and value not in EFFORT_LEVEL_VALUES:
            raise CopilotSyncError(f"launcher.defaultArgs --effort must be one of: {', '.join(sorted(EFFORT_LEVEL_VALUES))}")
        if flag == "--mode" and value not in MODE_VALUES:
            raise CopilotSyncError(f"launcher.defaultArgs --mode must be one of: {', '.join(sorted(MODE_VALUES))}")
        if flag == "--model" and value not in MODEL_VALUES:
            raise CopilotSyncError(f"launcher.defaultArgs --model must be one of: {', '.join(sorted(MODEL_VALUES))}")
        if flag == "--max-autopilot-continues" and not value.isdigit():
            raise CopilotSyncError("launcher.defaultArgs --max-autopilot-continues must be a positive integer")
        idx += 2


def validate_launcher(launcher: dict[str, Any]) -> None:
    unknown = sorted(set(launcher) - LAUNCHER_KEYS)
    if unknown:
        raise CopilotSyncError(f"launcher has unknown keys: {', '.join(unknown)}")
    if "enabled" in launcher and not isinstance(launcher["enabled"], bool):
        raise CopilotSyncError("launcher.enabled must be a boolean")
    default_args = launcher.get("defaultArgs", [])
    if not isinstance(default_args, list) or not all(isinstance(item, str) and item for item in default_args):
        raise CopilotSyncError("launcher.defaultArgs must be an array of non-empty strings")
    validate_launcher_args(default_args)
    management_commands = launcher.get("managementCommands", [])
    if not isinstance(management_commands, list) or not all(isinstance(item, str) and item for item in management_commands):
        raise CopilotSyncError("launcher.managementCommands must be an array of non-empty strings")
    unknown_commands = sorted(set(management_commands) - MANAGEMENT_COMMANDS)
    if unknown_commands:
        raise CopilotSyncError(f"launcher.managementCommands has unknown commands: {', '.join(unknown_commands)}")


def validate_skills(skills: dict[str, Any]) -> None:
    allowed = {
        "appSkillsPolicy",
        "copilotSkillDirectoryPolicy",
        "expectedAppBundledSkills",
        "projectGithubSkillDirectoryPolicy",
    }
    unknown = sorted(set(skills) - allowed)
    if unknown:
        raise CopilotSyncError(f"skills has unknown keys: {', '.join(unknown)}")
    for key in ("copilotSkillDirectoryPolicy", "projectGithubSkillDirectoryPolicy"):
        if key in skills and skills[key] not in SKILL_DIRECTORY_POLICIES:
            raise CopilotSyncError(f"skills.{key} must be one of: {', '.join(sorted(SKILL_DIRECTORY_POLICIES))}")
    if "appSkillsPolicy" in skills and skills["appSkillsPolicy"] not in APP_SKILLS_POLICIES:
        raise CopilotSyncError(f"skills.appSkillsPolicy must be one of: {', '.join(sorted(APP_SKILLS_POLICIES))}")
    expected = skills.get("expectedAppBundledSkills", [])
    if not isinstance(expected, list) or not all(isinstance(item, str) and item for item in expected):
        raise CopilotSyncError("skills.expectedAppBundledSkills must be an array of non-empty strings")


def validate_hooks_overlay(hooks: dict[str, Any]) -> None:
    allowed = {"forbiddenCommandSubstrings", "managedCopilotHooks", "userHookFile"}
    unknown = sorted(set(hooks) - allowed)
    if unknown:
        raise CopilotSyncError(f"hooks has unknown keys: {', '.join(unknown)}")
    if "managedCopilotHooks" in hooks and not isinstance(hooks["managedCopilotHooks"], bool):
        raise CopilotSyncError("hooks.managedCopilotHooks must be a boolean")
    if "userHookFile" in hooks and not isinstance(hooks["userHookFile"], str):
        raise CopilotSyncError("hooks.userHookFile must be a string")
    forbidden = hooks.get("forbiddenCommandSubstrings", [])
    if not isinstance(forbidden, list) or not all(isinstance(item, str) and item for item in forbidden):
        raise CopilotSyncError("hooks.forbiddenCommandSubstrings must be an array of non-empty strings")


def validate_mcp_servers(mcp_servers: dict[str, Any]) -> None:
    for name, entry in mcp_servers.items():
        if not isinstance(name, str) or not name.strip():
            raise CopilotSyncError(f"mcpServers has invalid server name: {name!r}")
        if not isinstance(entry, dict):
            raise CopilotSyncError(f"mcpServers.{name} must be an object")
        unknown = sorted(set(entry) - MCP_SERVER_KEYS)
        if unknown:
            raise CopilotSyncError(f"mcpServers.{name} has unknown keys: {', '.join(unknown)}")
        server_type = entry.get("type")
        if server_type not in MCP_SERVER_TYPES:
            raise CopilotSyncError(f"mcpServers.{name}.type must be one of: {', '.join(sorted(MCP_SERVER_TYPES))}")
        if server_type == "local":
            if not isinstance(entry.get("command"), str) or not entry["command"].strip():
                raise CopilotSyncError(f"mcpServers.{name}.command must be a non-empty string for local servers")
            args = entry.get("args", [])
            if not isinstance(args, list) or not all(isinstance(item, str) for item in args):
                raise CopilotSyncError(f"mcpServers.{name}.args must be an array of strings")
            env = entry.get("env", {})
            if not isinstance(env, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in env.items()):
                raise CopilotSyncError(f"mcpServers.{name}.env must be an object of string values")
            if "url" in entry or "headers" in entry:
                raise CopilotSyncError(f"mcpServers.{name} must not set url/headers for a local server")
        else:
            if not isinstance(entry.get("url"), str) or not entry["url"].strip():
                raise CopilotSyncError(f"mcpServers.{name}.url must be a non-empty string for {server_type} servers")
            headers = entry.get("headers", {})
            if not isinstance(headers, dict) or not all(isinstance(k, str) and isinstance(v, str) for k, v in headers.items()):
                raise CopilotSyncError(f"mcpServers.{name}.headers must be an object of string values")
            if "command" in entry or "args" in entry or "env" in entry:
                raise CopilotSyncError(f"mcpServers.{name} must not set command/args/env for a {server_type} server")
        tools = entry.get("tools", ["*"])
        if not isinstance(tools, list) or not all(isinstance(item, str) for item in tools):
            raise CopilotSyncError(f"mcpServers.{name}.tools must be an array of strings")
        if "timeout" in entry and not isinstance(entry["timeout"], int):
            raise CopilotSyncError(f"mcpServers.{name}.timeout must be an integer")


def load_overlay(path: Path) -> dict[str, Any]:
    data = read_json_object(path)
    unknown_top_level = sorted(set(data) - TOP_LEVEL_KEYS)
    if unknown_top_level:
        raise CopilotSyncError(f"config/copilot-settings.json has unknown top-level keys: {', '.join(unknown_top_level)}")
    settings = data.get("settings", {})
    if not isinstance(settings, dict):
        raise CopilotSyncError("config/copilot-settings.json settings must be an object")
    validate_managed_settings(settings)
    settings_prune = data.get("settingsPrune", [])
    if not isinstance(settings_prune, list) or not all(isinstance(item, str) for item in settings_prune):
        raise CopilotSyncError("config/copilot-settings.json settingsPrune must be an array of strings")
    validate_settings_prune(settings_prune)
    trust = data.get("trust", {})
    if not isinstance(trust, dict):
        raise CopilotSyncError("config/copilot-settings.json trust must be an object")
    validate_trust(trust)
    launcher = data.get("launcher", {})
    if not isinstance(launcher, dict):
        raise CopilotSyncError("config/copilot-settings.json launcher must be an object")
    validate_launcher(launcher)
    skills = data.get("skills", {})
    if not isinstance(skills, dict):
        raise CopilotSyncError("config/copilot-settings.json skills must be an object")
    validate_skills(skills)
    hooks = data.get("hooks", {})
    if not isinstance(hooks, dict):
        raise CopilotSyncError("config/copilot-settings.json hooks must be an object")
    validate_hooks_overlay(hooks)
    mcp_servers = data.get("mcpServers", {})
    if not isinstance(mcp_servers, dict):
        raise CopilotSyncError("config/copilot-settings.json mcpServers must be an object")
    validate_mcp_servers(mcp_servers)
    return data


def supported_setting_value(value: Any) -> bool:
    if isinstance(value, (str, bool, int, float)) or value is None:
        return True
    if isinstance(value, list):
        return all(isinstance(item, str) for item in value)
    if isinstance(value, dict):
        return all(isinstance(key, str) and supported_setting_value(item) for key, item in value.items())
    return False


def merge_settings(existing: dict[str, Any], overlay: dict[str, Any]) -> dict[str, Any]:
    desired = dict(existing)
    for key in overlay.get("settingsPrune", []):
        desired.pop(key, None)
    for key, value in overlay.get("settings", {}).items():
        if supported_setting_value(value):
            desired[key] = value
        else:
            raise CopilotSyncError(f"unsupported managed Copilot setting value: {key}")
    return desired


def normalized_path_list(raw: Any) -> list[str]:
    if not isinstance(raw, list):
        return []
    result: list[str] = []
    seen: set[str] = set()
    for value in raw:
        if not isinstance(value, str) or not value.strip():
            continue
        expanded = str(Path(value).expanduser().resolve())
        if expanded in seen:
            continue
        seen.add(expanded)
        result.append(expanded)
    return result


def merge_trusted_folders(*sources: Any) -> list[str]:
    merged: list[str] = []
    seen: set[str] = set()
    for source in sources:
        for expanded in normalized_path_list(source):
            if expanded in seen:
                continue
            seen.add(expanded)
            merged.append(expanded)
    return merged


def discover_trusted_folders(overlay: dict[str, Any], github_root: Path, home: Path) -> list[str]:
    trust = overlay.get("trust", {})
    trusted: list[Path] = []

    if trust.get("githubRoot", False):
        trusted.append(github_root)
    if trust.get("directChildren", False) and github_root.is_dir():
        trusted.extend(path for path in sorted(github_root.iterdir()) if path.is_dir())

    extras = trust.get("extraFolders", [])
    if not isinstance(extras, list):
        raise CopilotSyncError("trust.extraFolders must be an array")
    for raw in extras:
        if not isinstance(raw, str) or not raw.strip():
            raise CopilotSyncError(f"invalid trust.extraFolders entry: {raw!r}")
        trusted.append(expand_path(raw.strip(), home))

    seen: set[str] = set()
    result: list[str] = []
    for path in trusted:
        resolved = path.expanduser().resolve()
        if not resolved.exists():
            continue
        value = str(resolved)
        if value in seen:
            continue
        seen.add(value)
        result.append(value)
    return result


def remove_settings_trust(existing_settings: dict[str, Any]) -> dict[str, Any]:
    desired = dict(existing_settings)
    desired.pop("trustedFolders", None)
    return desired


def merge_user_config(
    existing: dict[str, Any],
    existing_settings: dict[str, Any],
    trusted_folders: list[str],
) -> dict[str, Any]:
    desired = dict(existing)
    desired["trustedFolders"] = merge_trusted_folders(
        existing.get("trustedFolders", []),
        existing_settings.get("trustedFolders", []),
        trusted_folders,
    )
    return desired


def render_mcp_config(mcp_servers: dict[str, Any]) -> dict[str, Any]:
    rendered: dict[str, Any] = {}
    for name in sorted(mcp_servers):
        entry = mcp_servers[name]
        server_type = entry["type"]
        out: dict[str, Any] = {"tools": entry.get("tools", ["*"]), "type": server_type}
        if server_type == "local":
            out["command"] = entry["command"]
            out["args"] = entry.get("args", [])
            if entry.get("env"):
                out["env"] = entry["env"]
        else:
            out["url"] = entry["url"]
            if entry.get("headers"):
                out["headers"] = entry["headers"]
        if "timeout" in entry:
            out["timeout"] = entry["timeout"]
        rendered[name] = out
    return {"mcpServers": rendered}


def write_json(path: Path, data: dict[str, Any], *, apply: bool, header: str = "") -> None:
    rendered = header + json.dumps(data, indent=2, sort_keys=False) + "\n"
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == rendered:
        print(f"UNCHANGED {path}")
        return
    print(f"SYNC {path}")
    if not apply:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(rendered, encoding="utf-8")


def ensure_str(value: Any, field: str, label: str, idx: int) -> str:
    if not isinstance(value, str) or not value.strip():
        raise CopilotSyncError(f"{label}[{idx}] invalid {field}: {value!r}")
    return value.strip()


def shell_home_path(path: Path) -> str:
    try:
        rel = path.resolve().relative_to(Path.home().resolve())
    except ValueError:
        return str(path)
    return "${HOME}/" + rel.as_posix()


def shell_home_path_unbraced(path: Path) -> str:
    try:
        rel = path.resolve().relative_to(Path.home().resolve())
    except ValueError:
        return str(path)
    return "$HOME/" + rel.as_posix()


def copilot_workspace_repo_root(repo_root: Path) -> str:
    fallback = shell_home_path_unbraced(repo_root)
    return "${COPILOT_WORKSPACE_PATH:-" + fallback + "}"


def shell_quote_command_part(part: str) -> str:
    if part.startswith("${HOME}/"):
        return '"' + part.replace('"', '\\"') + '"'
    return shlex.quote(part)


def shell_command_preserving_home(parts: list[str]) -> str:
    return " ".join(shell_quote_command_part(part) for part in parts)


def shell_command(parts: list[str]) -> str:
    return " ".join(shlex.quote(part) for part in parts)


def expand_dev_server_runtime_value(value: str, github_root: Path, repo_root: Path) -> str:
    github_root_value = shell_home_path(github_root)
    repo_root_value = copilot_workspace_repo_root(repo_root)
    return (
        value.replace("{github_root}", github_root_value)
        .replace("{repo_root}", repo_root_value)
    )


def repo_git_root(path: Path) -> Path | None:
    if not path.exists():
        return None
    result = subprocess.run(
        ["git", "-C", str(path), "rev-parse", "--show-toplevel"],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        check=False,
    )
    if result.returncode != 0:
        return None
    root = result.stdout.strip()
    return Path(root).resolve() if root else None


def load_dev_servers(registry_file: Path) -> list[dict[str, Any]]:
    data = read_json_object(registry_file)
    raw_items = data.get("managed_dev_servers", [])
    if not isinstance(raw_items, list):
        raise CopilotSyncError("managed_dev_servers must be an array")
    entries: list[dict[str, Any]] = []
    seen_ports: dict[int, str] = {}
    for idx, item in enumerate(raw_items):
        if not isinstance(item, dict):
            raise CopilotSyncError(f"managed_dev_servers[{idx}] must be an object")
        repo = ensure_str(item.get("repo"), "repo", "managed_dev_servers", idx)
        servers_raw = item.get("servers", [])
        if not isinstance(servers_raw, list) or not servers_raw:
            raise CopilotSyncError(f"managed_dev_servers[{idx}] needs a non-empty servers array")
        if len(servers_raw) != 1:
            raise CopilotSyncError(
                f"managed_dev_servers[{idx}] must define exactly one agent preview server"
            )
        servers: list[dict[str, Any]] = []
        label = f"managed_dev_servers[{idx}].servers"
        for sidx, server in enumerate(servers_raw):
            if not isinstance(server, dict):
                raise CopilotSyncError(f"{label}[{sidx}] must be an object")
            name = ensure_str(server.get("name"), "name", label, sidx)
            runtime = ensure_str(server.get("runtimeExecutable"), "runtimeExecutable", label, sidx)
            host = str(server.get("host", "127.0.0.1")).strip() or "127.0.0.1"
            args_raw = server.get("runtimeArgs", [])
            if not isinstance(args_raw, list) or not all(isinstance(arg, str) for arg in args_raw):
                raise CopilotSyncError(f"{label}[{sidx}] runtimeArgs must be an array of strings")
            port = server.get("port")
            if not isinstance(port, int) or isinstance(port, bool):
                raise CopilotSyncError(f"{label}[{sidx}] port must be an integer")
            if port in seen_ports:
                raise CopilotSyncError(f"{label}[{sidx}] port {port} duplicates {seen_ports[port]}")
            seen_ports[port] = f"{repo}/{name}"
            port_token = str(port)
            for arg in args_raw:
                if port_token in arg and "{port}" not in arg:
                    raise CopilotSyncError(
                        f"{label}[{sidx}] hardcodes port {port} in runtimeArgs; "
                        "use the {port} placeholder so the port stays single-source"
                    )
            runtime_args = [
                arg.replace("{port}", port_token).replace("{host}", host) for arg in args_raw
            ]
            auto_port = server.get("autoPort", False)
            if not isinstance(auto_port, bool):
                raise CopilotSyncError(f"{label}[{sidx}] autoPort must be a boolean")
            if auto_port:
                raise CopilotSyncError(
                    f"{label}[{sidx}] autoPort must be false for shared agent previews"
                )
            servers.append(
                {
                    "name": name,
                    "host": host,
                    "runtimeExecutable": runtime,
                    "runtimeArgs": runtime_args,
                    "port": port,
                    "autoPort": False,
                }
            )
        entries.append({"repo": repo, "servers": servers})

    seen: set[str] = set()
    duplicates = sorted(
        entry["repo"] for entry in entries if entry["repo"] in seen or seen.add(entry["repo"])
    )
    if duplicates:
        raise CopilotSyncError(f"duplicate dev-server repo entries: {', '.join(duplicates)}")
    return entries


def preview_command_parts(
    server: dict[str, Any],
    preview_runner: Path,
    github_root: Path,
    repo_root: Path,
) -> list[str]:
    wrapped = [
        "python3",
        shell_home_path(preview_runner),
        "--host",
        server["host"],
        "--port",
        str(server["port"]),
        "--",
        expand_dev_server_runtime_value(server["runtimeExecutable"], github_root, repo_root),
        *[
            expand_dev_server_runtime_value(arg, github_root, repo_root)
            for arg in server["runtimeArgs"]
        ],
    ]
    return ["/bin/bash", "-lc", shell_command_preserving_home(wrapped)]


def yaml_single_quoted(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def github_app_config_text(
    entry: dict[str, Any],
    preview_runner: Path,
    github_root: Path,
    repo_root: Path,
) -> str:
    server = entry["servers"][0]
    command = shell_command(preview_command_parts(server, preview_runner, github_root, repo_root))
    return "\n".join(
        [
            GITHUB_APP_CONFIG_HEADER.rstrip(),
            "# Source: ~/GitHub/agents/dev-servers/registry.json",
            "scripts:",
            f"  run: {yaml_single_quoted(command)}",
            f"server_ready_pattern: {yaml_single_quoted(GITHUB_APP_SERVER_READY_PATTERN)}",
            "auto_open_in_browser: true",
            "",
        ]
    )


def render_text_file(target: Path, desired: str, *, apply: bool, label: str) -> None:
    existing = target.read_text(encoding="utf-8") if target.is_file() else None
    if existing == desired:
        print(f"UNCHANGED {target}")
        return
    print(f"SYNC {target} ({label})")
    if not apply:
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(desired, encoding="utf-8")


def iter_dev_server_repo_targets(
    entries: list[dict[str, Any]],
    github_root: Path,
    repo_filters: set[Path],
) -> list[tuple[dict[str, Any], Path]]:
    home = Path.home()
    targets: list[tuple[dict[str, Any], Path]] = []
    for entry in entries:
        repo_root = resolve_repo_root(entry["repo"], github_root, home)
        if repo_filters and repo_root not in repo_filters:
            continue
        actual_repo = repo_git_root(repo_root)
        if actual_repo is None:
            if repo_root.exists():
                print(f"WARNING: skipping existing non-git path: {repo_root}", file=sys.stderr)
            continue
        if repo_filters and actual_repo not in repo_filters:
            continue
        targets.append((entry, actual_repo))
    return targets


def render_github_app_configs(
    entries: list[dict[str, Any]],
    github_root: Path,
    repo_filters: set[Path],
    preview_runner: Path,
    *,
    apply: bool,
) -> None:
    for entry, repo_root in iter_dev_server_repo_targets(entries, github_root, repo_filters):
        target = repo_root / ".github" / "github-app.yml"
        render_text_file(
            target,
            github_app_config_text(entry, preview_runner, github_root, repo_root),
            apply=apply,
            label="GitHub Copilot app preview config",
        )


def render_launcher_content(real_cli_path: Path, default_args: list[str], management_commands: list[str]) -> str:
    quoted_defaults = " ".join(json.dumps(arg) for arg in default_args)
    command_cases = "|".join(sorted(management_commands))
    return f"""#!/usr/bin/env bash
set -euo pipefail

real_cli="${{COPILOT_REAL_CLI_PATH:-{real_cli_path}}}"
if [[ ! -x "$real_cli" ]]; then
  printf 'ERROR: managed Copilot launcher cannot find executable: %s\\n' "$real_cli" >&2
  exit 127
fi

secret_env="${{COPILOT_SECRET_ENV:-$HOME/.secrets/copilot-cli/env}}"
if [[ -f "$secret_env" ]]; then
  set -a
  source "$secret_env"
  set +a
fi

if [[ "${{COPILOT_DISABLE_MANAGED_DEFAULTS:-}}" == "1" ]]; then
  exec "$real_cli" "$@"
fi

management=0
for arg in "$@"; do
  case "$arg" in
    -h|--help|-v|--version)
      management=1
      break
      ;;
    --)
      break
      ;;
    -*)
      continue
      ;;
    {command_cases})
      management=1
      break
      ;;
    *)
      break
      ;;
  esac
done

if (( management == 1 )); then
  exec "$real_cli" "$@"
fi

exec "$real_cli" {quoted_defaults} "$@"
"""


def render_launcher(
    target: Path,
    real_cli_path: Path,
    overlay: dict[str, Any],
    *,
    apply: bool,
) -> None:
    launcher = overlay.get("launcher", {})
    if not launcher.get("enabled", True):
        print(f"SKIP {target} (launcher disabled)")
        return
    default_args = launcher.get("defaultArgs", [])
    if not isinstance(default_args, list) or not all(isinstance(arg, str) for arg in default_args):
        raise CopilotSyncError("launcher.defaultArgs must be an array of strings")
    management_commands = launcher.get("managementCommands", sorted(MANAGEMENT_COMMANDS))
    if not isinstance(management_commands, list) or not all(isinstance(arg, str) for arg in management_commands):
        raise CopilotSyncError("launcher.managementCommands must be an array of strings")
    content = render_launcher_content(real_cli_path, default_args, management_commands)
    existing = target.read_text(encoding="utf-8") if target.exists() and target.is_file() else None
    if existing == content:
        print(f"UNCHANGED {target}")
        return
    print(f"SYNC {target} (managed Copilot launcher)")
    if not apply:
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.exists() or target.is_symlink():
        target.unlink()
    target.write_text(content, encoding="utf-8")
    target.chmod(0o755)


def render_hooks_file(
    hooks_file: Path,
    hooks_registry_file: Path,
    overlay: dict[str, Any],
    *,
    apply: bool,
) -> None:
    hooks = overlay.get("hooks", {})
    if not hooks.get("managedCopilotHooks", False):
        print(f"SKIP {hooks_file} (managed Copilot hooks disabled)")
        return
    registry = load_hooks_registry(hooks_registry_file)
    desired = render_copilot_hooks(registry)
    rendered = render_json(desired)
    existing = hooks_file.read_text(encoding="utf-8") if hooks_file.exists() else None
    if existing == rendered:
        print(f"UNCHANGED {hooks_file}")
        return
    print(f"SYNC {hooks_file} (managed Copilot hooks)")
    if not apply:
        return
    hooks_file.parent.mkdir(parents=True, exist_ok=True)
    hooks_file.write_text(rendered, encoding="utf-8")


def rel_link(dst: Path, src: Path) -> str:
    return os.path.relpath(str(src), str(dst.parent))


def resolved_symlink_target(link_path: Path) -> Path:
    current = os.readlink(link_path)
    if os.path.isabs(current):
        return Path(current).resolve()
    return (link_path.parent / current).resolve()


def render_global_instructions(target: Path, source: Path, *, apply: bool) -> None:
    if not source.is_file():
        raise CopilotSyncError(f"missing canonical global instructions source: {source}")
    if target.is_symlink() and resolved_symlink_target(target) == source.resolve():
        print(f"UNCHANGED {target}")
        return
    rel = rel_link(target, source)
    print(f"SYNC {target} -> {rel}")
    if not apply:
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    if target.is_symlink() or target.is_file():
        target.unlink()
    target.symlink_to(rel)


def sync(
    overlay_file: Path,
    hooks_registry_file: Path,
    dev_servers_registry: Path,
    settings_file: Path,
    user_config_file: Path,
    mcp_config_file: Path,
    hooks_file: Path,
    launcher_target: Path,
    real_cli_path: Path,
    github_root: Path,
    repo_filters: set[Path],
    preview_runner: Path,
    global_instructions_source: Path,
    global_instructions_target: Path,
    *,
    apply: bool,
    skip_github_app_configs: bool,
    skip_global_instructions: bool,
) -> None:
    overlay = load_overlay(overlay_file)
    home = settings_file.expanduser().resolve().parents[0].parent

    settings = read_json_object(settings_file, allow_comments=True)
    user_config = read_json_object(user_config_file, allow_comments=True)
    trusted_folders = discover_trusted_folders(overlay, github_root, home)
    desired_settings = merge_settings(settings, overlay)
    desired_settings = remove_settings_trust(desired_settings)
    write_json(settings_file, desired_settings, apply=apply)

    desired_user_config = merge_user_config(user_config, settings, trusted_folders)
    write_json(user_config_file, desired_user_config, apply=apply, header=CONFIG_HEADER)

    desired_mcp_config = render_mcp_config(overlay.get("mcpServers", {}))
    write_json(mcp_config_file, desired_mcp_config, apply=apply, header=CONFIG_HEADER)

    render_hooks_file(hooks_file, hooks_registry_file, overlay, apply=apply)
    render_launcher(launcher_target, real_cli_path, overlay, apply=apply)
    if not skip_global_instructions:
        render_global_instructions(global_instructions_target, global_instructions_source, apply=apply)
    if not skip_github_app_configs:
        render_github_app_configs(
            load_dev_servers(dev_servers_registry),
            github_root,
            repo_filters,
            preview_runner,
            apply=apply,
        )


def fail(message: str) -> None:
    raise CopilotSyncError(message)


def json_contains_forbidden(value: Any, forbidden: list[str]) -> bool:
    rendered = json.dumps(value, sort_keys=True, default=str)
    return any(item in rendered for item in forbidden)


def run_cli_json(real_cli_path: Path, args: list[str]) -> Any:
    result = subprocess.run(
        [str(real_cli_path), *args],
        check=False,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        fail(
            f"Copilot CLI command failed: {real_cli_path} {' '.join(args)}\n"
            f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        )
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        fail(f"Copilot CLI did not return JSON for {' '.join(args)}: {exc}")


def app_skill_names(app_support_dir: Path) -> list[str]:
    app_skills = app_support_dir / "app-skills"
    if not app_skills.is_dir():
        return []
    return sorted(path.name for path in app_skills.iterdir() if (path / "SKILL.md").is_file())


def direct_skill_copies(root: Path) -> list[Path]:
    if not root.exists():
        return []
    return sorted(root.glob("*/SKILL.md"))


def repo_github_skill_copies(github_root: Path) -> list[Path]:
    if not github_root.is_dir():
        return []
    skill_files: list[Path] = []
    for repo in sorted(path for path in github_root.iterdir() if path.is_dir()):
        skill_files.extend(direct_skill_copies(repo / ".github/skills"))
    return sorted(skill_files)


def check(
    overlay_file: Path,
    hooks_registry_file: Path,
    dev_servers_registry: Path,
    settings_file: Path,
    user_config_file: Path,
    mcp_config_file: Path,
    hooks_file: Path,
    launcher_target: Path,
    real_cli_path: Path,
    github_root: Path,
    repo_filters: set[Path],
    preview_runner: Path,
    app_support_dir: Path,
    global_instructions_source: Path,
    global_instructions_target: Path,
    *,
    skip_cli_probe: bool,
    skip_github_app_configs: bool,
    skip_global_instructions: bool,
) -> None:
    overlay = load_overlay(overlay_file)
    actual_settings = read_json_object(settings_file, allow_comments=True)
    user_config = read_json_object(user_config_file, allow_comments=True)
    expected_settings = merge_settings(actual_settings, overlay)
    for key, expected_value in overlay.get("settings", {}).items():
        if actual_settings.get(key) != expected_value:
            fail(f"Copilot setting drift: {settings_file} {key}={actual_settings.get(key)!r}, expected {expected_value!r}")

    expected_mcp_config = render_mcp_config(overlay.get("mcpServers", {}))
    actual_mcp_config = read_json_object(mcp_config_file, allow_comments=True)
    if actual_mcp_config != expected_mcp_config:
        fail(f"Copilot MCP config is out of sync: {mcp_config_file}")

    forbidden = overlay.get("hooks", {}).get("forbiddenCommandSubstrings", [])
    if not isinstance(forbidden, list) or not all(isinstance(item, str) for item in forbidden):
        fail("hooks.forbiddenCommandSubstrings must be an array of strings")
    if json_contains_forbidden(actual_settings.get("hooks", {}), forbidden):
        fail(f"forbidden Copilot hook command is still present in {settings_file}")

    home = settings_file.expanduser().resolve().parents[0].parent
    expected_trusted = set(discover_trusted_folders(overlay, github_root, home))
    duplicate_settings_trust = sorted(
        expected_trusted
        & set(normalized_path_list(actual_settings.get("trustedFolders", [])))
    )
    if duplicate_settings_trust:
        fail(f"managed Copilot trustedFolders still duplicated in {settings_file}: {duplicate_settings_trust[0]}")
    actual_trusted_raw = user_config.get("trustedFolders", [])
    if not isinstance(actual_trusted_raw, list):
        fail(f"trustedFolders must be an array in {user_config_file}")
    actual_trusted = {str(Path(path).expanduser().resolve()) for path in actual_trusted_raw if isinstance(path, str)}
    missing_trusted = sorted(expected_trusted - actual_trusted)
    if missing_trusted:
        fail(f"Copilot config trustedFolders missing {len(missing_trusted)} entries, first missing: {missing_trusted[0]}")
    if json_contains_forbidden(user_config.get("hooks", {}), forbidden):
        fail(f"forbidden Copilot hook command is still present in {user_config_file}")

    if overlay.get("hooks", {}).get("managedCopilotHooks", False):
        expected_hooks = render_json(render_copilot_hooks(load_hooks_registry(hooks_registry_file)))
        if not hooks_file.is_file():
            fail(f"missing managed Copilot hooks file: {hooks_file}")
        if hooks_file.read_text(encoding="utf-8") != expected_hooks:
            fail(f"managed Copilot hooks file is out of sync: {hooks_file}")

    launcher = overlay.get("launcher", {})
    if launcher.get("enabled", True):
        expected_launcher = render_launcher_content(
            real_cli_path,
            launcher.get("defaultArgs", []),
            launcher.get("managementCommands", sorted(MANAGEMENT_COMMANDS)),
        )
        if not launcher_target.is_file():
            fail(f"missing managed Copilot launcher: {launcher_target}")
        if launcher_target.read_text(encoding="utf-8") != expected_launcher:
            fail(f"managed Copilot launcher is out of sync: {launcher_target}")
        if not os.access(launcher_target, os.X_OK):
            fail(f"managed Copilot launcher is not executable: {launcher_target}")

    if not skip_global_instructions:
        if not global_instructions_source.is_file():
            fail(f"missing canonical global instructions source: {global_instructions_source}")
        if not global_instructions_target.is_symlink():
            fail(f"missing managed Copilot global instructions symlink: {global_instructions_target}")
        if resolved_symlink_target(global_instructions_target) != global_instructions_source.resolve():
            fail(f"Copilot global instructions symlink is out of sync: {global_instructions_target}")

    if not skip_github_app_configs:
        for entry, repo_root in iter_dev_server_repo_targets(
            load_dev_servers(dev_servers_registry),
            github_root,
            repo_filters,
        ):
            target = repo_root / ".github" / "github-app.yml"
            expected = github_app_config_text(entry, preview_runner, github_root, repo_root)
            if not target.is_file():
                fail(f"missing GitHub Copilot app preview config: {target}")
            if target.read_text(encoding="utf-8") != expected:
                fail(f"GitHub Copilot app preview config is out of sync: {target}")

    copilot_skill_dir = settings_file.parent / "skills"
    if overlay.get("skills", {}).get("copilotSkillDirectoryPolicy") == "empty":
        skill_files = direct_skill_copies(copilot_skill_dir)
        if skill_files:
            fail(f"unexpected direct Copilot skill copies under {copilot_skill_dir}: {skill_files[0]}")
    if overlay.get("skills", {}).get("projectGithubSkillDirectoryPolicy") == "empty":
        skill_files = repo_github_skill_copies(github_root)
        if skill_files:
            fail(f"unexpected project Copilot skill copies under .github/skills: {skill_files[0]}")

    if not real_cli_path.is_file() or not os.access(real_cli_path, os.X_OK):
        fail(f"missing executable Copilot CLI: {real_cli_path}")
    if not skip_cli_probe:
        skills = run_cli_json(real_cli_path, ["skill", "list", "--json"])
        if not isinstance(skills, list):
            fail("Copilot CLI skill list JSON must be an array")
        app_skills_path = str((app_support_dir / "app-skills").resolve())
        for item in skills:
            if isinstance(item, dict) and str(item.get("path", "")).startswith(app_skills_path):
                fail(f"Copilot CLI is loading app-bundled skill as CLI skill: {item.get('name')}")
        mcp = run_cli_json(real_cli_path, ["mcp", "list", "--json"])
        if not isinstance(mcp, dict):
            fail("Copilot CLI MCP list JSON must be an object")
        live_servers = mcp.get("mcpServers", {})
        if not isinstance(live_servers, dict):
            fail("Copilot CLI MCP list JSON mcpServers must be an object")
        for name in overlay.get("mcpServers", {}):
            live_entry = live_servers.get(name)
            if not isinstance(live_entry, dict) or live_entry.get("source") != "user":
                fail(f"managed Copilot MCP server not loaded from user config: {name}")

    observed_app_skills = app_skill_names(app_support_dir)
    if overlay.get("skills", {}).get("appSkillsPolicy") == "allow-known-only":
        expected = overlay.get("skills", {}).get("expectedAppBundledSkills", [])
        if not isinstance(expected, list) or not all(isinstance(item, str) for item in expected):
            fail("skills.expectedAppBundledSkills must be an array of strings")
        unexpected = sorted(set(observed_app_skills) - set(expected))
        if unexpected:
            fail(f"unexpected Copilot app bundled skills: {', '.join(unexpected)}")
    if observed_app_skills:
        print("OBSERVE Copilot app bundled skills: " + ", ".join(observed_app_skills))
    print("Copilot control plane OK")
    _ = expected_settings


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Sync or validate managed GitHub Copilot CLI settings, trust, launcher, and skill-noise policy."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--apply", action="store_true", help="Apply managed Copilot state.")
    mode.add_argument("--check", action="store_true", help="Validate managed Copilot state.")
    mode.add_argument("--dry-run", action="store_true", help="Show managed writes without applying.")
    parser.add_argument("--settings-overlay", default=str(DEFAULT_SETTINGS_OVERLAY), help="Canonical Copilot settings overlay.")
    parser.add_argument("--hooks-registry", default=str(DEFAULT_HOOKS_REGISTRY), help="Canonical lifecycle hooks registry.")
    parser.add_argument("--dev-servers-registry", default=str(DEFAULT_DEV_SERVERS_REGISTRY), help="Canonical dev-server registry for GitHub Copilot app run configs.")
    parser.add_argument("--preview-runner", default=str(DEFAULT_PREVIEW_RUNNER), help="Shared preview runner used by generated app run configs.")
    parser.add_argument("--settings-file", default=str(DEFAULT_SETTINGS_FILE), help="Target ~/.copilot/settings.json.")
    parser.add_argument("--user-config-file", default=str(DEFAULT_USER_CONFIG_FILE), help="Target ~/.copilot/config.json.")
    parser.add_argument("--mcp-config-file", default=str(DEFAULT_MCP_CONFIG_FILE), help="Target ~/.copilot/mcp-config.json.")
    parser.add_argument("--hooks-file", default=str(DEFAULT_HOOKS_FILE), help="Target managed Copilot user hooks file.")
    parser.add_argument("--launcher-target", default=str(DEFAULT_LAUNCHER_TARGET), help="Managed terminal launcher target.")
    parser.add_argument("--real-cli-path", default=str(DEFAULT_REAL_CLI_PATH), help="Real Copilot CLI executable.")
    parser.add_argument("--github-root", default=str(DEFAULT_GITHUB_ROOT), help="GitHub workspace root to trust.")
    parser.add_argument("--repo", action="append", default=[], help="Limit repo-local GitHub Copilot app config sync/check to an exact repo path or repo name.")
    parser.add_argument("--app-support-dir", default=str(DEFAULT_APP_SUPPORT_DIR), help="GitHub Copilot app support directory.")
    parser.add_argument("--skip-github-app-configs", action="store_true", help="Do not render/check per-repo .github/github-app.yml preview configs.")
    parser.add_argument("--skip-cli-probe", action="store_true", help="Skip live copilot skill/mcp CLI probes during --check.")
    parser.add_argument("--global-instructions-source", default=str(DEFAULT_GLOBAL_INSTRUCTIONS_SOURCE), help="Canonical machine-wide guidance source for Copilot global instructions.")
    parser.add_argument("--global-instructions-target", default=str(DEFAULT_GLOBAL_INSTRUCTIONS_TARGET), help="Target ~/.copilot/copilot-instructions.md.")
    parser.add_argument("--skip-global-instructions", action="store_true", help="Do not render/check the global Copilot instructions symlink.")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    overlay_file = output_path(Path(args.settings_overlay))
    hooks_registry_file = output_path(Path(args.hooks_registry))
    dev_servers_registry = output_path(Path(args.dev_servers_registry)).resolve()
    settings_file = output_path(Path(args.settings_file))
    user_config_file = output_path(Path(args.user_config_file))
    mcp_config_file = output_path(Path(args.mcp_config_file))
    hooks_file = output_path(Path(args.hooks_file))
    launcher_target = output_path(Path(args.launcher_target))
    real_cli_path = output_path(Path(args.real_cli_path))
    github_root = output_path(Path(args.github_root)).resolve()
    preview_runner = output_path(Path(args.preview_runner)).resolve()
    repo_filters = {
        resolve_repo_root(raw.strip(), github_root, Path.home())
        for raw in args.repo
        if raw.strip()
    }
    app_support_dir = output_path(Path(args.app_support_dir)).resolve()
    global_instructions_source = output_path(Path(args.global_instructions_source)).resolve()
    raw_global_instructions_target = output_path(Path(args.global_instructions_target))
    global_instructions_target = raw_global_instructions_target.parent.resolve() / raw_global_instructions_target.name

    try:
        if args.check:
            check(
                overlay_file,
                hooks_registry_file,
                dev_servers_registry,
                settings_file,
                user_config_file,
                mcp_config_file,
                hooks_file,
                launcher_target,
                real_cli_path,
                github_root,
                repo_filters,
                preview_runner,
                app_support_dir,
                global_instructions_source,
                global_instructions_target,
                skip_cli_probe=args.skip_cli_probe,
                skip_github_app_configs=args.skip_github_app_configs,
                skip_global_instructions=args.skip_global_instructions,
            )
        else:
            sync(
                overlay_file,
                hooks_registry_file,
                dev_servers_registry,
                settings_file,
                user_config_file,
                mcp_config_file,
                hooks_file,
                launcher_target,
                real_cli_path,
                github_root,
                repo_filters,
                preview_runner,
                global_instructions_source,
                global_instructions_target,
                apply=args.apply,
                skip_github_app_configs=args.skip_github_app_configs,
                skip_global_instructions=args.skip_global_instructions,
            )
    except CopilotSyncError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
